language: node_js
sudo: required
dist: trusty
os:
  - linux
  - osx
node_js: 12

env:
  - CC=gcc CXX=gcc npm_config_clang=1

notifications:
  email: false

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+?(-\S*)?$/

services:
  - docker

cache:
  directories:
  - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libx11-dev
      - python-gnomekeyring

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi
script:
  - npm run prebuild-node
  - npm run prebuild-electron
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t clipboard-data/i386 docker/i386 && docker run --rm -v ${PWD}:/project clipboard-data/i386 /bin/bash -c "cd /project && npm run prebuild-node-ia32 && npm run prebuild-electron-ia32"; fi
  - if [[ -n "$TRAVIS_TAG" ]]; then npm run upload; fi